#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 13:24:31 2020

@author: hamishgibbs
"""


import __main__ as main
import sys
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

if not hasattr(main, '__file__'):
    argv = ['code', '/Users/hamishgibbs/Documents/Covid-19/facebook_mobility_uk/data/interim/crisis_baseline_comparison.csv']
else:
    argv = sys.argv
    
cb_comp = pd.read_csv(argv[1])


#%%

g = sns.FacetGrid(cb_comp, col="period")
g.map(sns.scatterplot, "n_baseline", "n_crisis", data = cb_comp)
